[tool.poetry]
name = "poetryproject"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
domonic = "^0.9.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"